### ISSUE TITLE
Possibility to make the stack executable

### ISSUE THREAD

**Issue by jfma7** [arget13/DDexec#2]
Hello:

Sometimes we would like to run code on the stack. For example, a msfvenom reverse shell in C that is written and executed from the stack.

Right now the code does not support stack execution but it could be an option for the future.

Greetings.

**Comment by arget13** [comment]
Yes, this I think should be easy to implement. When iterating over the program header entries we would need to check if there is any entry of type `GNU_STACK` and check if its permissions include execution, if so then add another piece of shellcode to call `mprotect()`.

Since this is a feature request I may take my time to do this.
